[package]
name = "zsh-seq"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "zsh_seq"
path = "src/lib.rs"

[[bin]]
name = "zsh_seq_cli"
path = "src/main.rs"